version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5550:5500"
    volumes:
      - ./dist:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "node --watch app.js"

  db:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongodb:/data/db
    restart: on-failure
    ports:
      - "27018:27017"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html