export enum ECarBrand {
  Audi = "Audi",
  BMW = "BMW",
  Chevrolet = "Chevrolet",
  Ford = "Ford",
  Honda = "Honda",
  Hyundai = "Hyundai",
  KIA = "KIA",
  Lexus = "Lexus",
  Mazda = "Mazda",
  Mercedes = "Mercedes",
  Mitsubishi = "Mitsubishi",
  Nissan = "Nissan",
  Opel = "Opel",
  Peugeot = "Peugeot",
  Renault = "Renault",
  Skoda = "Skoda",
  Toyota = "Toyota",
  Volkswagen = "Volkswagen",
}
