export enum EEmailEnum {
  REGISTER = "REGISTER",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_EMAIL = "CHANGE_EMAIL",
  ACTIVATE_EMAIL = "ACTIVATE_EMAIL",
}
